services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pw
    secrets:
      - pg_user
      - pg_pw
    volumes:
      - ./data:/var/lib/postgresql/data
    command: >
      postgres -c log_statement=all
               -c log_connections=on
               -c log_disconnections=on
               -c shared_preload_libraries=pg_stat_statements
               -c pg_stat_statements.track=all
    restart: unless-stopped
    network_mode: "host"
    healthcheck:
      test: pg_isready -U admin -d postgres
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s

secrets:
  pg_user:
    file: ./secrets/pg_user.txt
  pg_pw:
    file: ./secrets/pg_pw.txt